version: "3.8"

services:
  entradas:
    build: entradas/.
    container_name: entradas
    ports:
      - "5001:5000"
    restart: always
    hostname: entradas
  eventos:
    build: eventos/.
    container_name: eventos
    ports:
      - "5002:5000"
    restart: always
    hostname: eventos
  usuarios:
    build: usuarios/.
    container_name: usuarios
    ports:
      - "5003:5000"
    restart: always
    hostname: usuarios
