import { Product } from "./types";

export const products: Product[] = [
  // Cars & Models
  {
    id: "1",
    name: "Red Bull RB19 Replica",
    driver: "Max Verstappen",
    team: "Red Bull Racing",
    category: "Car",
    price: 89.99,
    picture:
      "https://resources.claroshop.com/medios-plazavip/fotos/productos_sears1/original/4091992.jpg",
    description: "Official Red Bull Racing RB19 replica model car",
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "Ferrari SF-23 Die-Cast Model",
    driver: "Charles Leclerc",
    team: "Scuderia Ferrari",
    category: "Car",
    price: 149.99,
    picture:
      "https://cdn11.bigcommerce.com/s-rejby4tfjq/images/stencil/1000x667/products/15131/77582/18-26808-16-MAI-Bburago-Ferrari-SF-23-No16-Charles-Leclerc-F1-2023-1__69265.1729296412.jpg?c=1",
    description:
      "Limited edition Ferrari SF-23 die-cast model with Leclerc livery",
    inStock: false,
    featured: true,
  },
  {
    id: "3",
    name: "Mercedes W14 Scale Model",
    driver: "Lewis Hamilton",
    team: "Mercedes AMG F1",
    category: "Car",
    price: 119.99,
    picture:
      "https://shop-int.mercedesamgf1.com/cdn/shop/files/JW6268_1_HARDWARE_Photography_FrontCenterView_grey150125.jpg",
    description: "Detailed Mercedes W14 scale model from the 2023 season",
    inStock: true,
    featured: false,
  },
  {
    id: "4",
    name: "McLaren MCL60 Model",
    driver: "Lando Norris",
    team: "McLaren F1 Team",
    category: "Car",
    price: 99.99,
    picture:
      "https://images.footballfanatics.com/mclaren-f1-team/mclaren-f1-team-lando-norris-2024-1:5-spark-model-helmet_ss5_p-201710614+pv-2+u-wiaaj9oafikhzdezfbx5+v-l61r3iymn1cklkazxm1n.jpg",
    description: "McLaren MCL60 official replica model",
    inStock: true,
    featured: false,
  },
  {
    id: "5",
    name: "Aston Martin AMR23",
    driver: "Fernando Alonso",
    team: "Aston Martin F1 Team",
    category: "Car",
    price: 134.99,
    picture: "https://m.media-amazon.com/images/I/71sz6YgEmAL.jpg",
    description: "Aston Martin AMR23 detailed replica model",
    inStock: true,
    featured: false,
  },

  // Merchandise
  {
    id: "6",
    name: "Mercedes AMG F1 Team Cap",
    driver: "Kimi Antonelli",
    team: "Mercedes AMG F1",
    category: "Merchandise",
    price: 29.99,
    picture:
      "https://shop-int.mercedesamgf1.com/cdn/shop/files/JW6268_1_HARDWARE_Photography_FrontCenterView_grey150125.jpg",
    description: "Official Mercedes AMG F1 team cap",
    inStock: true,
    featured: false,
  },
  {
    id: "7",
    name: "Red Bull Racing Team Polo",
    driver: "Max Verstappen",
    team: "Red Bull Racing",
    category: "Merchandise",
    price: 49.99,
    picture:
      "https://images.footballfanatics.com/red-bull-racing/oracle-red-bull-racing-2022-team-polo_ss4_p-13300699+u-2e78bwhasmsuzi5zyiun+v-c201179ba83d4aeea1d46bdc9f96dfb4.jpg?_hv=2",
    description: "Official Red Bull Racing team polo shirt",
    inStock: true,
    featured: true,
  },
  {
    id: "8",
    name: "Ferrari Team Hoodie",
    driver: "Charles Leclerc",
    team: "Scuderia Ferrari",
    category: "Merchandise",
    price: 79.99,
    picture:
      "https://images.footballfanatics.com/scuderia-ferrari/scuderia-ferrari-2024-team-hooded-sweat_ss5_p-201131541+u-opxxjzsgpkyt59bicuqm+v-jgmzpxd7wqw23zrg4x4g.jpg?_hv=2",
    description: "Premium Ferrari team hoodie with official branding",
    inStock: true,
    featured: false,
  },
  {
    id: "9",
    name: "McLaren Team T-Shirt",
    driver: "Oscar Piastri",
    team: "McLaren F1 Team",
    category: "Merchandise",
    price: 34.99,
    picture:
      "https://fanatics.frgimages.com/mclaren-f1-team/mens-castore-oscar-piastri-charcoal-mclaren-f1-team-replica-set-up-driver-t-shirt_ss5_p-200588687+pv-1+u-sha5ygp7e7niwkh6agqd+v-igbac2jcjl9n0yokrgx1.jpg?_hv=2&w=900",
    description: "Comfortable McLaren team t-shirt in papaya orange",
    inStock: true,
    featured: false,
  },
  {
    id: "10",
    name: "Alpine F1 Team Jacket",
    driver: "Pierre Gasly",
    team: "Alpine F1 Team",
    category: "Merchandise",
    price: 79.99,
    picture:
      "https://images.footballfanatics.com/alpine/alpine-f1-team-2024-rain-jacket_ss5_p-200837889+u-mxazpxczp49uvhjqycvu+v-xobs7q3v7hhgkco9yff7.jpg",
    description: "Official Alpine F1 Team jacket worn by the pit crew",
    inStock: true,
    featured: false,
  },
  {
    id: "11",
    name: "Aston Martin Team Cap",
    driver: "Lance Stroll",
    team: "Aston Martin F1 Team",
    category: "Merchandise",
    price: 32.99,
    picture: "https://m.media-amazon.com/images/I/51GWuhyUNVL._AC_SL1000_.jpg",
    description: "Aston Martin F1 team cap in signature green",
    inStock: true,
    featured: false,
  },

  // Collectibles
  {
    id: "12",
    name: "Lewis Hamilton Signed Photo",
    driver: "Lewis Hamilton",
    team: "Mercedes AMG F1",
    category: "Collectibles",
    price: 299.99,
    picture:
      "https://i.ebayimg.com/00/s/MTQ2MFgxMjA2/z/BIYAAOSwGWBj~1gF/$_57.JPG?set_id=880000500F",
    description: "Authentic signed photo of Lewis Hamilton with certificate",
    inStock: false,
    featured: true,
  },
  {
    id: "13",
    name: "Max Verstappen Championship Trophy Replica",
    driver: "Max Verstappen",
    team: "Red Bull Racing",
    category: "Collectibles",
    price: 189.99,
    picture: "https://i.ebayimg.com/images/g/05EAAOSwJyplJNrn/s-l1200.jpg",
    description: "Official replica of Max Verstappen's championship trophy",
    inStock: true,
    featured: true,
  },
  {
    id: "14",
    name: "Ferrari Steering Wheel Replica",
    driver: "Charles Leclerc",
    team: "Scuderia Ferrari",
    category: "Collectibles",
    price: 449.99,
    picture: "https://bosshunting.com.au/wp-content/uploads/2020/12/2-1.webp",
    description: "Detailed replica of Ferrari F1 steering wheel",
    inStock: true,
    featured: false,
  },
  {
    id: "15",
    name: "F1 Podium Trophy Set",
    driver: "Various",
    team: "Formula 1",
    category: "Collectibles",
    price: 99.99,
    picture:
      "https://media.gettyimages.com/id/2175957393/photo/trophies-at-formula-one-world-championship-rd2-bahrain-grand-prix-race-bahrain-international.jpg?s=612x612&w=gi&k=20&c=SvJLDadEZ-IChYoMi48cAleTMNbPKNXnP-YQdc9XHpo=",
    description: "Set of three F1 podium trophies (1st, 2nd, 3rd place)",
    inStock: true,
    featured: false,
  },

  // Racing Gear
  {
    id: "16",
    name: "McLaren Racing Helmet",
    driver: "Lando Norris",
    team: "McLaren F1 Team",
    category: "Racing Gear",
    price: 299.99,
    picture:
      "https://images.footballfanatics.com/mclaren-f1-team/mclaren-f1-team-lando-norris-2024-1:5-spark-model-helmet_ss5_p-201710614+pv-2+u-wiaaj9oafikhzdezfbx5+v-l61r3iymn1cklkazxm1n.jpg",
    description: "Professional grade racing helmet with McLaren F1 Team design",
    inStock: true,
    featured: false,
  },
  {
    id: "17",
    name: "F1 Racing Gloves",
    driver: "Various",
    team: "Formula 1",
    category: "Racing Gear",
    price: 149.99,
    picture:
      "https://beatracewears.com/cdn/shop/files/2021LewisHamiltonSignedRaceUsedMercedesAMGGloves_0007_Curves1.jpg?v=17200842940",
    description: "Professional F1-style racing gloves with grip technology",
    inStock: true,
    featured: false,
  },
  {
    id: "18",
    name: "Red Bull Racing Suit Replica",
    driver: "Sergio Perez",
    team: "Red Bull Racing",
    category: "Racing Gear",
    price: 99.99,
    picture:
      "https://aceracegear.com/wp-content/uploads/2023/07/2022-sergio-perez-red-bull-honda-f1-suit-1.jpg",
    description: "Official Red Bull Racing suit replica with all sponsors",
    inStock: false,
    featured: true,
  },
  {
    id: "19",
    name: "F1 Racing Boots",
    driver: "Various",
    team: "Formula 1",
    category: "Racing Gear",
    price: 249.99,
    picture:
      "https://us.f1authentics.com/cdn/shop/files/GeorgeRussell2023ReplicaBoots_6copy.jpg?v=1747142809",
    description: "Lightweight F1-style racing boots with ankle support",
    inStock: true,
    featured: false,
  },
  {
    id: "20",
    name: "Ferrari Team Radio Headset",
    driver: "Carlos Sainz",
    team: "Scuderia Ferrari",
    category: "Racing Gear",
    price: 179.99,
    picture:
      "https://www.topgear.com/sites/default/files/images/news-article/2018/11/37ca889b4394e17e2ff036e0ecfe2228/t-racingferraried_3.jpg",
    description: "Professional racing team radio headset",
    inStock: true,
    featured: false,
  },
  {
    id: "21",
    name: "Haas F1 Team Backpack",
    driver: "Kevin Magnussen",
    team: "MoneyGram Haas F1 Team",
    category: "Merchandise",
    price: 59.99,
    picture:
      "https://ih1.redbubble.net/image.3455712937.8216/ur,backpack_front,square,600x600.jpg",
    description: "Official Haas F1 team backpack with laptop compartment",
    inStock: true,
    featured: false,
  },
  {
    id: "22",
    name: "Williams Racing Watch",
    driver: "Alex Albon",
    team: "Williams Racing",
    category: "Collectibles",
    price: 399.99,
    picture:
      "https://cdn.williamsf1.tech/images/fnx611yr/production/bb0aff7842a53da9cf21e2d14974a64b43dd111a-5760x3840.jpg?rect=960,0,3840,3840&w=1200&h=1200&auto=format",
    description: "Limited edition Williams Racing chronograph watch",
    inStock: true,
    featured: true,
  },
  {
    id: "23",
    name: "AlphaTauri Team Sunglasses",
    driver: "Yuki Tsunoda",
    team: "Scuderia AlphaTauri",
    category: "Merchandise",
    price: 89.99,
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt-IHwQviPXSp0VXiq0gcXEZjqO4OHajJ16Q&s",
    description: "Stylish AlphaTauri team sunglasses with UV protection",
    inStock: true,
    featured: false,
  },
  {
    id: "24",
    name: "Monaco GP Commemorative Coin",
    driver: "Various",
    team: "Formula 1",
    category: "Collectibles",
    price: 79.99,
    picture: "https://i.ebayimg.com/images/g/DvgAAOxyu1BTkoOQ/s-l400.jpg",
    description: "Limited edition Monaco Grand Prix commemorative coin",
    inStock: true,
    featured: false,
  },
];
